AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Flow - Powerlifting Tracking App
  SAM Template for Flow backend services

# Global values that are applied to all resources
Globals:
  Function:
    Timeout: 30  # Lambda function timeout in seconds
    Runtime: python3.9
    MemorySize: 256
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        BLOCKS_TABLE: !Ref BlocksTable
        WEEKS_TABLE: !Ref WeeksTable
        DAYS_TABLE: !Ref DaysTable
        EXERCISES_TABLE: !Ref ExercisesTable
        WORKOUTS_TABLE: !Ref WorkoutsTable
        COMPLETED_EXERCISES_TABLE: !Ref CompletedExercisesTable
        RELATIONSHIPS_TABLE: !Ref RelationshipsTable
        LOG_LEVEL: INFO
        REGION: !Ref AWS::Region

Resources:
  # API Gateway Definition
  FlowAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt FlowUserPool.Arn
  
  # Cognito User Pool for Authentication
  FlowUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: flow-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: custom:role
          AttributeDataType: String
          Mutable: true
          Required: false
  
  # Cognito User Pool Client
  FlowUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: flow-user-pool-client
      UserPoolId: !Ref FlowUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
  
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  RelationshipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: relationship_id
          AttributeType: S
        - AttributeName: coach_id
          AttributeType: S
        - AttributeName: athlete_id
          AttributeType: S
      KeySchema:
        - AttributeName: relationship_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: coach-index
          KeySchema:
            - AttributeName: coach_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: athlete-index
          KeySchema:
            - AttributeName: athlete_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  BlocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: block_id
          AttributeType: S
        - AttributeName: athlete_id
          AttributeType: S
        - AttributeName: coach_id
          AttributeType: S
      KeySchema:
        - AttributeName: block_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: athlete-index
          KeySchema:
            - AttributeName: athlete_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: coach-index
          KeySchema:
            - AttributeName: coach_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  WeeksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: week_id
          AttributeType: S
        - AttributeName: block_id
          AttributeType: S
      KeySchema:
        - AttributeName: week_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: block-index
          KeySchema:
            - AttributeName: block_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  DaysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: day_id
          AttributeType: S
        - AttributeName: week_id
          AttributeType: S
      KeySchema:
        - AttributeName: day_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: week-index
          KeySchema:
            - AttributeName: week_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  ExercisesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: exercise_id
          AttributeType: S
        - AttributeName: day_id
          AttributeType: S
      KeySchema:
        - AttributeName: exercise_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: day-index
          KeySchema:
            - AttributeName: day_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  WorkoutsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: workout_id
          AttributeType: S
        - AttributeName: athlete_id
          AttributeType: S
        - AttributeName: day_id
          AttributeType: S
      KeySchema:
        - AttributeName: workout_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: athlete-index
          KeySchema:
            - AttributeName: athlete_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: day-index
          KeySchema:
            - AttributeName: day_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  CompletedExercisesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: completed_id
          AttributeType: S
        - AttributeName: workout_id
          AttributeType: S
        - AttributeName: exercise_id
          AttributeType: S
      KeySchema:
        - AttributeName: completed_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: workout-index
          KeySchema:
            - AttributeName: workout_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: exercise-index
          KeySchema:
            - AttributeName: exercise_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  # Main API Lambda function that handles all requests
  FlowApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.lambda_handler
      Description: Main Lambda handler for Flow API
      MemorySize: 512  # Increased memory for combined function
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref BlocksTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WeeksTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DaysTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ExercisesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkoutsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CompletedExercisesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RelationshipsTable
      Events:
        # User API Routes
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /users
            Method: post
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /users/{user_id}
            Method: get
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /users/{user_id}
            Method: put
            
        # Block API Routes
        CreateBlock:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /blocks
            Method: post
        GetBlock:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /blocks/{block_id}
            Method: get
        GetBlocksByAthlete:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /athletes/{athlete_id}/blocks
            Method: get
        UpdateBlock:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /blocks/{block_id}
            Method: put
        DeleteBlock:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /blocks/{block_id}
            Method: delete

        # Week API Routes
        CreateWeek:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /weeks
            Method: post
        GetWeeksForBlock:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /blocks/{block_id}/weeks
            Method: get
        UpdateWeek:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /weeks/{week_id}
            Method: put
        DeleteWeek:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /weeks/{week_id}
            Method: delete

        # Day API Routes
        CreateDay:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /days
            Method: post
        GetDaysForWeek:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /weeks/{week_id}/days
            Method: get
        UpdateDay:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /days/{day_id}
            Method: put
        DeleteDay:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /days/{day_id}
            Method: delete

        # Exercise API Routes
        CreateExercise:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /exercises
            Method: post
        GetExercisesForDay:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /days/{day_id}/exercises
            Method: get
        UpdateExercise:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /exercises/{exercise_id}
            Method: put
        DeleteExercise:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /exercises/{exercise_id}
            Method: delete
        ReorderExercises:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /exercises/reorder
            Method: post

        # Workout API Routes
        CreateWorkout:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /workouts
            Method: post
        GetWorkout:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /workouts/{workout_id}
            Method: get
        GetWorkoutsByAthlete:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /athletes/{athlete_id}/workouts
            Method: get
        UpdateWorkout:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /workouts/{workout_id}
            Method: put
        DeleteWorkout:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /workouts/{workout_id}
            Method: delete

        # Relationship API Routes
        CreateRelationship:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /relationships
            Method: post
        AcceptRelationship:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /relationships/{relationship_id}/accept
            Method: post
        EndRelationship:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /relationships/{relationship_id}/end
            Method: post
        GetCoachRelationships:
          Type: Api
          Properties:
            RestApiId: !Ref FlowAPI
            Path: /coaches/{coach_id}/relationships
            Method: get

Outputs:
  FlowApi:
    Description: API Gateway endpoint URL for dev stage
    Value: !Sub "https://${FlowAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref FlowUserPool
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref FlowUserPoolClient