AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Flow - Data Stack (DynamoDB Tables + Cognito)
  Persistent resources that rarely change

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name for resource naming
  LayerVersion:
    Type: String
    Default: v0.1.0
    Description: Version of layers to use

Resources:
  # Cognito User Pool for Authentication
  FlowUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "flow-${Environment}-user-pool"
      LambdaConfig:
       PostConfirmation: !GetAtt CognitoPostConfirmationFunction.Arn
      AdminCreateUserConfig:
       AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
       - email
      Schema:
       - Name: email
         AttributeDataType: String
         Mutable: true
         Required: true
       - Name: name
         AttributeDataType: String
         Mutable: true
         Required: true
       - Name: custom:role
         AttributeDataType: String
         Mutable: true
         Required: false
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  # Cognito User Pool Client
  FlowUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "flow-${Environment}-user-pool-client"
      UserPoolId: !Ref FlowUserPool
      ExplicitAuthFlows:
       - ALLOW_USER_PASSWORD_AUTH
       - ALLOW_REFRESH_TOKEN_AUTH
       - ALLOW_USER_SRP_AUTH
      GenerateSecret: false

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  RelationshipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-relationships"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: relationship_id
          AttributeType: S
        - AttributeName: coach_id
          AttributeType: S
        - AttributeName: athlete_id
          AttributeType: S
      KeySchema:
        - AttributeName: relationship_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: coach-index
          KeySchema:
            - AttributeName: coach_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: athlete-index
          KeySchema:
            - AttributeName: athlete_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: coach-athlete-index
          KeySchema:
            - AttributeName: coach_id
              KeyType: HASH
            - AttributeName: athlete_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  
  BlocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-blocks"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: block_id
          AttributeType: S
        - AttributeName: athlete_id
          AttributeType: S
        - AttributeName: coach_id
          AttributeType: S
      KeySchema:
        - AttributeName: block_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: athlete-index
          KeySchema:
            - AttributeName: athlete_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: coach-index
          KeySchema:
            - AttributeName: coach_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  WeeksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-weeks"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: week_id
          AttributeType: S
        - AttributeName: block_id
          AttributeType: S
      KeySchema:
        - AttributeName: week_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: block-index
          KeySchema:
            - AttributeName: block_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  DaysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-days"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: day_id
          AttributeType: S
        - AttributeName: week_id
          AttributeType: S
      KeySchema:
        - AttributeName: day_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: week-index
          KeySchema:
            - AttributeName: week_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  ExercisesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-exercises"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: exercise_id
          AttributeType: S
        - AttributeName: day_id
          AttributeType: S
        - AttributeName: workout_id
          AttributeType: S
      KeySchema:
        - AttributeName: exercise_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: day-index
          KeySchema:
            - AttributeName: day_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: workout-index
          KeySchema:
            - AttributeName: workout_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  WorkoutsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "flow-${Environment}-workouts"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: workout_id
          AttributeType: S
        - AttributeName: athlete_id
          AttributeType: S
        - AttributeName: day_id
          AttributeType: S
      KeySchema:
        - AttributeName: workout_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: athlete-index
          KeySchema:
            - AttributeName: athlete_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: day-index
          KeySchema:
            - AttributeName: day_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  
  CognitoPostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/cognito_triggers/
      Handler: post_confirmation_lambda.handler
      Runtime: python3.9
      Timeout: 30
      Layers:
        - !ImportValue
          Fn::Sub: "flow-layers-VendorLayerArn-${LayerVersion}"
        - !ImportValue
          Fn::Sub: "flow-layers-CommonLayerArn-${LayerVersion}"
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  # Lambda permission for Cognito to invoke the function
  CognitoTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CognitoPostConfirmationFunction.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt FlowUserPool.Arn

Outputs:
  UsersTableName:
    Description: Users DynamoDB table name
    Value: !Ref UsersTable
    Export:
      Name: !Sub "flow-${Environment}-UsersTable"
  
  RelationshipsTableName:
    Description: Relationships DynamoDB table name
    Value: !Ref RelationshipsTable
    Export:
      Name: !Sub "flow-${Environment}-RelationshipsTable"
  
  BlocksTableName:
    Description: Blocks DynamoDB table name
    Value: !Ref BlocksTable
    Export:
      Name: !Sub "flow-${Environment}-BlocksTable"
  
  WeeksTableName:
    Description: Weeks DynamoDB table name
    Value: !Ref WeeksTable
    Export:
      Name: !Sub "flow-${Environment}-WeeksTable"
  
  DaysTableName:
    Description: Days DynamoDB table name
    Value: !Ref DaysTable
    Export:
      Name: !Sub "flow-${Environment}-DaysTable"
  
  ExercisesTableName:
    Description: Exercises DynamoDB table name
    Value: !Ref ExercisesTable
    Export:
      Name: !Sub "flow-${Environment}-ExercisesTable"
  
  WorkoutsTableName:
    Description: Workouts DynamoDB table name
    Value: !Ref WorkoutsTable
    Export:
      Name: !Sub "flow-${Environment}-WorkoutsTable"
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref FlowUserPool
    Export:
      Name: !Sub "flow-${Environment}-UserPoolId"
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref FlowUserPoolClient
    Export:
      Name: !Sub "flow-${Environment}-UserPoolClientId"
  
  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt FlowUserPool.Arn
    Export:
      Name: !Sub "flow-${Environment}-UserPoolArn"