AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layers for Flow App

Parameters:
  LayerVersion:
    Type: String
    Default: v0-1-0
    Description: Semantic version for layer exports
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name for resource naming

Conditions:
  IsProdEnvironment: !Equals [!Ref Environment, "prod"]
  IsDevEnvironment: !Equals [!Ref Environment, "dev"]

Resources:
  VendorLayerProd:
    Type: AWS::Serverless::LayerVersion
    Condition: IsProdEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-vendor-layer"
      Description: !Sub "Third-party dependencies for Flow app (${Environment})"
      ContentUri: layers/vendor/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  VendorLayerDev:
    Type: AWS::Serverless::LayerVersion
    Condition: IsDevEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-vendor-layer"
      Description: !Sub "Third-party dependencies for Flow app (${Environment})"
      ContentUri: layers/vendor/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

  CommonLayerProd:
    Type: AWS::Serverless::LayerVersion
    Condition: IsProdEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-common-layer"
      Description: !Sub "Common utilities and shared code for Flow app (${Environment})"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  CommonLayerDev:
    Type: AWS::Serverless::LayerVersion
    Condition: IsDevEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-common-layer"
      Description: !Sub "Common utilities and shared code for Flow app (${Environment})"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
  
  CommonLayerParameterProd:
    Type: AWS::SSM::Parameter
    Condition: IsProdEnvironment
    Properties:
      Name: !Sub "/flow/${Environment}/layers/common/arn"
      Type: String
      Value: !Ref CommonLayerProd
      Description: !Sub "Common layer ARN for ${Environment}"
      
  CommonLayerParameterDev:
    Type: AWS::SSM::Parameter
    Condition: IsDevEnvironment
    Properties:
      Name: !Sub "/flow/${Environment}/layers/common/arn"
      Type: String
      Value: !Ref CommonLayerDev
      Description: !Sub "Common layer ARN for ${Environment}"
      
  VendorLayerParameterProd:
    Type: AWS::SSM::Parameter
    Condition: IsProdEnvironment
    Properties:
      Name: !Sub "/flow/${Environment}/layers/vendor/arn"
      Type: String
      Value: !Ref VendorLayerProd
      Description: !Sub "Vendor layer ARN for ${Environment}"
      
  VendorLayerParameterDev:
    Type: AWS::SSM::Parameter
    Condition: IsDevEnvironment
    Properties:
      Name: !Sub "/flow/${Environment}/layers/vendor/arn"
      Type: String
      Value: !Ref VendorLayerDev
      Description: !Sub "Vendor layer ARN for ${Environment}"
