AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layers for Flow App

Parameters:
  LayerVersion:
    Type: String
    Default: v0-1-0
    Description: Semantic version for layer exports (underscores for CloudFormation compatibility)

Resources:
  VendorLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: flow-vendor-layer
      Description: Third-party dependencies for Flow app
      ContentUri: layers/vendor/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: flow-common-layer
      Description: Common utilities and shared code for Flow app
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

Outputs:
  VendorLayerArn:
    Description: ARN for the Vendor Layer
    Value: !Ref VendorLayer
    Export:
      Name: !Sub "flow-layers-VendorLayerArn-${LayerVersion}"

  CommonLayerArn:
    Description: ARN for the Common Layer
    Value: !Ref CommonLayer
    Export:
      Name: !Sub "flow-layers-CommonLayerArn-${LayerVersion}"