AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layers for Flow App

Parameters:
  LayerVersion:
    Type: String
    Default: v0-1-0
    Description: Semantic version for layer exports
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name for resource naming

Conditions:
  IsProdEnvironment: !Equals [!Ref Environment, "prod"]
  IsDevEnvironment: !Equals [!Ref Environment, "dev"]

Resources:
  VendorLayerProd:
    Type: AWS::Serverless::LayerVersion
    Condition: IsProdEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-vendor-layer"
      Description: !Sub "Third-party dependencies for Flow app (${Environment})"
      ContentUri: layers/vendor/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  VendorLayerDev:
    Type: AWS::Serverless::LayerVersion
    Condition: IsDevEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-vendor-layer"
      Description: !Sub "Third-party dependencies for Flow app (${Environment})"
      ContentUri: layers/vendor/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

  CommonLayerProd:
    Type: AWS::Serverless::LayerVersion
    Condition: IsProdEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-common-layer"
      Description: !Sub "Common utilities and shared code for Flow app (${Environment})"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  CommonLayerDev:
    Type: AWS::Serverless::LayerVersion
    Condition: IsDevEnvironment
    Properties:
      LayerName: !Sub "flow-${Environment}-common-layer"
      Description: !Sub "Common utilities and shared code for Flow app (${Environment})"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

Outputs:
  VendorLayerArn:
    Description: "ARN for the Vendor Layer"
    Value: !If [IsProdEnvironment, !Ref VendorLayerProd, !Ref VendorLayerDev]
    Export:
      Name: !Sub "flow-${Environment}-VendorLayerArn-${LayerVersion}"

  CommonLayerArn:
    Description: "ARN for the Common Layer"
    Value: !If [IsProdEnvironment, !Ref CommonLayerProd, !Ref CommonLayerDev]
    Export:
      Name: !Sub "flow-${Environment}-CommonLayerArn-${LayerVersion}"
